# golangci-lint configuration for v2.x
# Based on official documentation: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    # 核心质量检查
    - errcheck      # 检查未处理的错误
    - govet         # 检查可疑构造
    - ineffassign   # 检查未使用的赋值
    - staticcheck   # 静态分析检查
    - unused        # 检查未使用的常量、变量、函数和类型

  exclusions:
    # 排除测试文件和生成的protobuf文件
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck
      - path: '(.+)\.pb\.go'
        linters:
          - errcheck
          - staticcheck
          - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 