# golangci-lint configuration 
# Optimized for CI compatibility and core quality checks
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # 核心质量检查 - 已测试有效
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    # 排除测试文件
    - path: _test\.go
      linters:
        - errcheck
    
    # 排除生成的protobuf文件
    - path: ".*\\.pb\\.go$"
      linters:
        - errcheck
        - staticcheck
        - unused

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0 