// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: burndevice/v1/service.proto

package burndevicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DestructionType int32

const (
	DestructionType_DESTRUCTION_TYPE_UNSPECIFIED         DestructionType = 0
	DestructionType_DESTRUCTION_TYPE_FILE_DELETION       DestructionType = 1
	DestructionType_DESTRUCTION_TYPE_REGISTRY_CORRUPTION DestructionType = 2
	DestructionType_DESTRUCTION_TYPE_SERVICE_TERMINATION DestructionType = 3
	DestructionType_DESTRUCTION_TYPE_MEMORY_EXHAUSTION   DestructionType = 4
	DestructionType_DESTRUCTION_TYPE_DISK_FILL           DestructionType = 5
	DestructionType_DESTRUCTION_TYPE_NETWORK_DISRUPTION  DestructionType = 6
	DestructionType_DESTRUCTION_TYPE_BOOT_CORRUPTION     DestructionType = 7
	DestructionType_DESTRUCTION_TYPE_KERNEL_PANIC        DestructionType = 8
)

// Enum value maps for DestructionType.
var (
	DestructionType_name = map[int32]string{
		0: "DESTRUCTION_TYPE_UNSPECIFIED",
		1: "DESTRUCTION_TYPE_FILE_DELETION",
		2: "DESTRUCTION_TYPE_REGISTRY_CORRUPTION",
		3: "DESTRUCTION_TYPE_SERVICE_TERMINATION",
		4: "DESTRUCTION_TYPE_MEMORY_EXHAUSTION",
		5: "DESTRUCTION_TYPE_DISK_FILL",
		6: "DESTRUCTION_TYPE_NETWORK_DISRUPTION",
		7: "DESTRUCTION_TYPE_BOOT_CORRUPTION",
		8: "DESTRUCTION_TYPE_KERNEL_PANIC",
	}
	DestructionType_value = map[string]int32{
		"DESTRUCTION_TYPE_UNSPECIFIED":         0,
		"DESTRUCTION_TYPE_FILE_DELETION":       1,
		"DESTRUCTION_TYPE_REGISTRY_CORRUPTION": 2,
		"DESTRUCTION_TYPE_SERVICE_TERMINATION": 3,
		"DESTRUCTION_TYPE_MEMORY_EXHAUSTION":   4,
		"DESTRUCTION_TYPE_DISK_FILL":           5,
		"DESTRUCTION_TYPE_NETWORK_DISRUPTION":  6,
		"DESTRUCTION_TYPE_BOOT_CORRUPTION":     7,
		"DESTRUCTION_TYPE_KERNEL_PANIC":        8,
	}
)

func (x DestructionType) Enum() *DestructionType {
	p := new(DestructionType)
	*p = x
	return p
}

func (x DestructionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DestructionType) Descriptor() protoreflect.EnumDescriptor {
	return file_burndevice_v1_service_proto_enumTypes[0].Descriptor()
}

func (DestructionType) Type() protoreflect.EnumType {
	return &file_burndevice_v1_service_proto_enumTypes[0]
}

func (x DestructionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DestructionType.Descriptor instead.
func (DestructionType) EnumDescriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{0}
}

type DestructionSeverity int32

const (
	DestructionSeverity_DESTRUCTION_SEVERITY_UNSPECIFIED DestructionSeverity = 0
	DestructionSeverity_DESTRUCTION_SEVERITY_LOW         DestructionSeverity = 1 // Recoverable
	DestructionSeverity_DESTRUCTION_SEVERITY_MEDIUM      DestructionSeverity = 2 // Requires manual intervention
	DestructionSeverity_DESTRUCTION_SEVERITY_HIGH        DestructionSeverity = 3 // System reinstall required
	DestructionSeverity_DESTRUCTION_SEVERITY_CRITICAL    DestructionSeverity = 4 // Hardware replacement may be needed
)

// Enum value maps for DestructionSeverity.
var (
	DestructionSeverity_name = map[int32]string{
		0: "DESTRUCTION_SEVERITY_UNSPECIFIED",
		1: "DESTRUCTION_SEVERITY_LOW",
		2: "DESTRUCTION_SEVERITY_MEDIUM",
		3: "DESTRUCTION_SEVERITY_HIGH",
		4: "DESTRUCTION_SEVERITY_CRITICAL",
	}
	DestructionSeverity_value = map[string]int32{
		"DESTRUCTION_SEVERITY_UNSPECIFIED": 0,
		"DESTRUCTION_SEVERITY_LOW":         1,
		"DESTRUCTION_SEVERITY_MEDIUM":      2,
		"DESTRUCTION_SEVERITY_HIGH":        3,
		"DESTRUCTION_SEVERITY_CRITICAL":    4,
	}
)

func (x DestructionSeverity) Enum() *DestructionSeverity {
	p := new(DestructionSeverity)
	*p = x
	return p
}

func (x DestructionSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DestructionSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_burndevice_v1_service_proto_enumTypes[1].Descriptor()
}

func (DestructionSeverity) Type() protoreflect.EnumType {
	return &file_burndevice_v1_service_proto_enumTypes[1]
}

func (x DestructionSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DestructionSeverity.Descriptor instead.
func (DestructionSeverity) EnumDescriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{1}
}

type DestructionEventType int32

const (
	DestructionEventType_DESTRUCTION_EVENT_TYPE_UNSPECIFIED DestructionEventType = 0
	DestructionEventType_DESTRUCTION_EVENT_TYPE_STARTED     DestructionEventType = 1
	DestructionEventType_DESTRUCTION_EVENT_TYPE_PROGRESS    DestructionEventType = 2
	DestructionEventType_DESTRUCTION_EVENT_TYPE_COMPLETED   DestructionEventType = 3
	DestructionEventType_DESTRUCTION_EVENT_TYPE_ERROR       DestructionEventType = 4
	DestructionEventType_DESTRUCTION_EVENT_TYPE_WARNING     DestructionEventType = 5
)

// Enum value maps for DestructionEventType.
var (
	DestructionEventType_name = map[int32]string{
		0: "DESTRUCTION_EVENT_TYPE_UNSPECIFIED",
		1: "DESTRUCTION_EVENT_TYPE_STARTED",
		2: "DESTRUCTION_EVENT_TYPE_PROGRESS",
		3: "DESTRUCTION_EVENT_TYPE_COMPLETED",
		4: "DESTRUCTION_EVENT_TYPE_ERROR",
		5: "DESTRUCTION_EVENT_TYPE_WARNING",
	}
	DestructionEventType_value = map[string]int32{
		"DESTRUCTION_EVENT_TYPE_UNSPECIFIED": 0,
		"DESTRUCTION_EVENT_TYPE_STARTED":     1,
		"DESTRUCTION_EVENT_TYPE_PROGRESS":    2,
		"DESTRUCTION_EVENT_TYPE_COMPLETED":   3,
		"DESTRUCTION_EVENT_TYPE_ERROR":       4,
		"DESTRUCTION_EVENT_TYPE_WARNING":     5,
	}
)

func (x DestructionEventType) Enum() *DestructionEventType {
	p := new(DestructionEventType)
	*p = x
	return p
}

func (x DestructionEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DestructionEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_burndevice_v1_service_proto_enumTypes[2].Descriptor()
}

func (DestructionEventType) Type() protoreflect.EnumType {
	return &file_burndevice_v1_service_proto_enumTypes[2]
}

func (x DestructionEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DestructionEventType.Descriptor instead.
func (DestructionEventType) EnumDescriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{2}
}

type ExecuteDestructionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               DestructionType        `protobuf:"varint,1,opt,name=type,proto3,enum=burndevice.v1.DestructionType" json:"type,omitempty"`
	Targets            []string               `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	Severity           DestructionSeverity    `protobuf:"varint,3,opt,name=severity,proto3,enum=burndevice.v1.DestructionSeverity" json:"severity,omitempty"`
	ConfirmDestruction bool                   `protobuf:"varint,4,opt,name=confirm_destruction,json=confirmDestruction,proto3" json:"confirm_destruction,omitempty"`
	AiScenarioId       string                 `protobuf:"bytes,5,opt,name=ai_scenario_id,json=aiScenarioId,proto3" json:"ai_scenario_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecuteDestructionRequest) Reset() {
	*x = ExecuteDestructionRequest{}
	mi := &file_burndevice_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteDestructionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteDestructionRequest) ProtoMessage() {}

func (x *ExecuteDestructionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_burndevice_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteDestructionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteDestructionRequest) Descriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteDestructionRequest) GetType() DestructionType {
	if x != nil {
		return x.Type
	}
	return DestructionType_DESTRUCTION_TYPE_UNSPECIFIED
}

func (x *ExecuteDestructionRequest) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *ExecuteDestructionRequest) GetSeverity() DestructionSeverity {
	if x != nil {
		return x.Severity
	}
	return DestructionSeverity_DESTRUCTION_SEVERITY_UNSPECIFIED
}

func (x *ExecuteDestructionRequest) GetConfirmDestruction() bool {
	if x != nil {
		return x.ConfirmDestruction
	}
	return false
}

func (x *ExecuteDestructionRequest) GetAiScenarioId() string {
	if x != nil {
		return x.AiScenarioId
	}
	return ""
}

type ExecuteDestructionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Results       []*DestructionResult   `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteDestructionResponse) Reset() {
	*x = ExecuteDestructionResponse{}
	mi := &file_burndevice_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteDestructionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteDestructionResponse) ProtoMessage() {}

func (x *ExecuteDestructionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_burndevice_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteDestructionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteDestructionResponse) Descriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteDestructionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteDestructionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteDestructionResponse) GetResults() []*DestructionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ExecuteDestructionResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StreamDestructionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               DestructionType        `protobuf:"varint,1,opt,name=type,proto3,enum=burndevice.v1.DestructionType" json:"type,omitempty"`
	Targets            []string               `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	Severity           DestructionSeverity    `protobuf:"varint,3,opt,name=severity,proto3,enum=burndevice.v1.DestructionSeverity" json:"severity,omitempty"`
	ConfirmDestruction bool                   `protobuf:"varint,4,opt,name=confirm_destruction,json=confirmDestruction,proto3" json:"confirm_destruction,omitempty"`
	AiScenarioId       string                 `protobuf:"bytes,5,opt,name=ai_scenario_id,json=aiScenarioId,proto3" json:"ai_scenario_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamDestructionRequest) Reset() {
	*x = StreamDestructionRequest{}
	mi := &file_burndevice_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDestructionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDestructionRequest) ProtoMessage() {}

func (x *StreamDestructionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_burndevice_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDestructionRequest.ProtoReflect.Descriptor instead.
func (*StreamDestructionRequest) Descriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *StreamDestructionRequest) GetType() DestructionType {
	if x != nil {
		return x.Type
	}
	return DestructionType_DESTRUCTION_TYPE_UNSPECIFIED
}

func (x *StreamDestructionRequest) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *StreamDestructionRequest) GetSeverity() DestructionSeverity {
	if x != nil {
		return x.Severity
	}
	return DestructionSeverity_DESTRUCTION_SEVERITY_UNSPECIFIED
}

func (x *StreamDestructionRequest) GetConfirmDestruction() bool {
	if x != nil {
		return x.ConfirmDestruction
	}
	return false
}

func (x *StreamDestructionRequest) GetAiScenarioId() string {
	if x != nil {
		return x.AiScenarioId
	}
	return ""
}

type StreamDestructionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Type          DestructionEventType   `protobuf:"varint,3,opt,name=type,proto3,enum=burndevice.v1.DestructionEventType" json:"type,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Progress      float64                `protobuf:"fixed64,5,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDestructionResponse) Reset() {
	*x = StreamDestructionResponse{}
	mi := &file_burndevice_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDestructionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDestructionResponse) ProtoMessage() {}

func (x *StreamDestructionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_burndevice_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDestructionResponse.ProtoReflect.Descriptor instead.
func (*StreamDestructionResponse) Descriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *StreamDestructionResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StreamDestructionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamDestructionResponse) GetType() DestructionEventType {
	if x != nil {
		return x.Type
	}
	return DestructionEventType_DESTRUCTION_EVENT_TYPE_UNSPECIFIED
}

func (x *StreamDestructionResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *StreamDestructionResponse) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type DestructionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Metrics       *DestructionMetrics    `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestructionResult) Reset() {
	*x = DestructionResult{}
	mi := &file_burndevice_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestructionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestructionResult) ProtoMessage() {}

func (x *DestructionResult) ProtoReflect() protoreflect.Message {
	mi := &file_burndevice_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestructionResult.ProtoReflect.Descriptor instead.
func (*DestructionResult) Descriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *DestructionResult) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DestructionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DestructionResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DestructionResult) GetMetrics() *DestructionMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type DestructionMetrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FilesDeleted         int64                  `protobuf:"varint,1,opt,name=files_deleted,json=filesDeleted,proto3" json:"files_deleted,omitempty"`
	BytesDestroyed       int64                  `protobuf:"varint,2,opt,name=bytes_destroyed,json=bytesDestroyed,proto3" json:"bytes_destroyed,omitempty"`
	ExecutionTimeSeconds float64                `protobuf:"fixed64,3,opt,name=execution_time_seconds,json=executionTimeSeconds,proto3" json:"execution_time_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DestructionMetrics) Reset() {
	*x = DestructionMetrics{}
	mi := &file_burndevice_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestructionMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestructionMetrics) ProtoMessage() {}

func (x *DestructionMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_burndevice_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestructionMetrics.ProtoReflect.Descriptor instead.
func (*DestructionMetrics) Descriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *DestructionMetrics) GetFilesDeleted() int64 {
	if x != nil {
		return x.FilesDeleted
	}
	return 0
}

func (x *DestructionMetrics) GetBytesDestroyed() int64 {
	if x != nil {
		return x.BytesDestroyed
	}
	return 0
}

func (x *DestructionMetrics) GetExecutionTimeSeconds() float64 {
	if x != nil {
		return x.ExecutionTimeSeconds
	}
	return 0
}

type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_burndevice_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_burndevice_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{6}
}

type GetSystemInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Os              string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Architecture    string                 `protobuf:"bytes,2,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Hostname        string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CriticalPaths   []string               `protobuf:"bytes,4,rep,name=critical_paths,json=criticalPaths,proto3" json:"critical_paths,omitempty"`
	RunningServices []string               `protobuf:"bytes,5,rep,name=running_services,json=runningServices,proto3" json:"running_services,omitempty"`
	Resources       *SystemResources       `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSystemInfoResponse) Reset() {
	*x = GetSystemInfoResponse{}
	mi := &file_burndevice_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResponse) ProtoMessage() {}

func (x *GetSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_burndevice_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetSystemInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *GetSystemInfoResponse) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *GetSystemInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetSystemInfoResponse) GetCriticalPaths() []string {
	if x != nil {
		return x.CriticalPaths
	}
	return nil
}

func (x *GetSystemInfoResponse) GetRunningServices() []string {
	if x != nil {
		return x.RunningServices
	}
	return nil
}

func (x *GetSystemInfoResponse) GetResources() *SystemResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

type SystemResources struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalMemory     int64                  `protobuf:"varint,1,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	AvailableMemory int64                  `protobuf:"varint,2,opt,name=available_memory,json=availableMemory,proto3" json:"available_memory,omitempty"`
	TotalDisk       int64                  `protobuf:"varint,3,opt,name=total_disk,json=totalDisk,proto3" json:"total_disk,omitempty"`
	AvailableDisk   int64                  `protobuf:"varint,4,opt,name=available_disk,json=availableDisk,proto3" json:"available_disk,omitempty"`
	CpuUsage        float64                `protobuf:"fixed64,5,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SystemResources) Reset() {
	*x = SystemResources{}
	mi := &file_burndevice_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemResources) ProtoMessage() {}

func (x *SystemResources) ProtoReflect() protoreflect.Message {
	mi := &file_burndevice_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemResources.ProtoReflect.Descriptor instead.
func (*SystemResources) Descriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *SystemResources) GetTotalMemory() int64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *SystemResources) GetAvailableMemory() int64 {
	if x != nil {
		return x.AvailableMemory
	}
	return 0
}

func (x *SystemResources) GetTotalDisk() int64 {
	if x != nil {
		return x.TotalDisk
	}
	return 0
}

func (x *SystemResources) GetAvailableDisk() int64 {
	if x != nil {
		return x.AvailableDisk
	}
	return 0
}

func (x *SystemResources) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

type GenerateAttackScenarioRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetDescription string                 `protobuf:"bytes,1,opt,name=target_description,json=targetDescription,proto3" json:"target_description,omitempty"`
	MaxSeverity       DestructionSeverity    `protobuf:"varint,2,opt,name=max_severity,json=maxSeverity,proto3,enum=burndevice.v1.DestructionSeverity" json:"max_severity,omitempty"`
	AiModel           string                 `protobuf:"bytes,3,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateAttackScenarioRequest) Reset() {
	*x = GenerateAttackScenarioRequest{}
	mi := &file_burndevice_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAttackScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAttackScenarioRequest) ProtoMessage() {}

func (x *GenerateAttackScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_burndevice_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAttackScenarioRequest.ProtoReflect.Descriptor instead.
func (*GenerateAttackScenarioRequest) Descriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateAttackScenarioRequest) GetTargetDescription() string {
	if x != nil {
		return x.TargetDescription
	}
	return ""
}

func (x *GenerateAttackScenarioRequest) GetMaxSeverity() DestructionSeverity {
	if x != nil {
		return x.MaxSeverity
	}
	return DestructionSeverity_DESTRUCTION_SEVERITY_UNSPECIFIED
}

func (x *GenerateAttackScenarioRequest) GetAiModel() string {
	if x != nil {
		return x.AiModel
	}
	return ""
}

type GenerateAttackScenarioResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId        string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Steps             []*AttackStep          `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	EstimatedSeverity DestructionSeverity    `protobuf:"varint,4,opt,name=estimated_severity,json=estimatedSeverity,proto3,enum=burndevice.v1.DestructionSeverity" json:"estimated_severity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateAttackScenarioResponse) Reset() {
	*x = GenerateAttackScenarioResponse{}
	mi := &file_burndevice_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAttackScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAttackScenarioResponse) ProtoMessage() {}

func (x *GenerateAttackScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_burndevice_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAttackScenarioResponse.ProtoReflect.Descriptor instead.
func (*GenerateAttackScenarioResponse) Descriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateAttackScenarioResponse) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *GenerateAttackScenarioResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GenerateAttackScenarioResponse) GetSteps() []*AttackStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *GenerateAttackScenarioResponse) GetEstimatedSeverity() DestructionSeverity {
	if x != nil {
		return x.EstimatedSeverity
	}
	return DestructionSeverity_DESTRUCTION_SEVERITY_UNSPECIFIED
}

type AttackStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         int32                  `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          DestructionType        `protobuf:"varint,3,opt,name=type,proto3,enum=burndevice.v1.DestructionType" json:"type,omitempty"`
	Targets       []string               `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	Rationale     string                 `protobuf:"bytes,5,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackStep) Reset() {
	*x = AttackStep{}
	mi := &file_burndevice_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackStep) ProtoMessage() {}

func (x *AttackStep) ProtoReflect() protoreflect.Message {
	mi := &file_burndevice_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackStep.ProtoReflect.Descriptor instead.
func (*AttackStep) Descriptor() ([]byte, []int) {
	return file_burndevice_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *AttackStep) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *AttackStep) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AttackStep) GetType() DestructionType {
	if x != nil {
		return x.Type
	}
	return DestructionType_DESTRUCTION_TYPE_UNSPECIFIED
}

func (x *AttackStep) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *AttackStep) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

var File_burndevice_v1_service_proto protoreflect.FileDescriptor

const file_burndevice_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bburndevice/v1/service.proto\x12\rburndevice.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x02\n" +
	"\x19ExecuteDestructionRequest\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.burndevice.v1.DestructionTypeR\x04type\x12\x18\n" +
	"\atargets\x18\x02 \x03(\tR\atargets\x12>\n" +
	"\bseverity\x18\x03 \x01(\x0e2\".burndevice.v1.DestructionSeverityR\bseverity\x12/\n" +
	"\x13confirm_destruction\x18\x04 \x01(\bR\x12confirmDestruction\x12$\n" +
	"\x0eai_scenario_id\x18\x05 \x01(\tR\faiScenarioId\"\xc6\x01\n" +
	"\x1aExecuteDestructionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\aresults\x18\x03 \x03(\v2 .burndevice.v1.DestructionResultR\aresults\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xff\x01\n" +
	"\x18StreamDestructionRequest\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.burndevice.v1.DestructionTypeR\x04type\x12\x18\n" +
	"\atargets\x18\x02 \x03(\tR\atargets\x12>\n" +
	"\bseverity\x18\x03 \x01(\x0e2\".burndevice.v1.DestructionSeverityR\bseverity\x12/\n" +
	"\x13confirm_destruction\x18\x04 \x01(\bR\x12confirmDestruction\x12$\n" +
	"\x0eai_scenario_id\x18\x05 \x01(\tR\faiScenarioId\"\xdc\x01\n" +
	"\x19StreamDestructionResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04type\x18\x03 \x01(\x0e2#.burndevice.v1.DestructionEventTypeR\x04type\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x01R\bprogress\"\xa7\x01\n" +
	"\x11DestructionResult\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12;\n" +
	"\ametrics\x18\x04 \x01(\v2!.burndevice.v1.DestructionMetricsR\ametrics\"\x98\x01\n" +
	"\x12DestructionMetrics\x12#\n" +
	"\rfiles_deleted\x18\x01 \x01(\x03R\ffilesDeleted\x12'\n" +
	"\x0fbytes_destroyed\x18\x02 \x01(\x03R\x0ebytesDestroyed\x124\n" +
	"\x16execution_time_seconds\x18\x03 \x01(\x01R\x14executionTimeSeconds\"\x16\n" +
	"\x14GetSystemInfoRequest\"\xf7\x01\n" +
	"\x15GetSystemInfoResponse\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\"\n" +
	"\farchitecture\x18\x02 \x01(\tR\farchitecture\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12%\n" +
	"\x0ecritical_paths\x18\x04 \x03(\tR\rcriticalPaths\x12)\n" +
	"\x10running_services\x18\x05 \x03(\tR\x0frunningServices\x12<\n" +
	"\tresources\x18\x06 \x01(\v2\x1e.burndevice.v1.SystemResourcesR\tresources\"\xc2\x01\n" +
	"\x0fSystemResources\x12!\n" +
	"\ftotal_memory\x18\x01 \x01(\x03R\vtotalMemory\x12)\n" +
	"\x10available_memory\x18\x02 \x01(\x03R\x0favailableMemory\x12\x1d\n" +
	"\n" +
	"total_disk\x18\x03 \x01(\x03R\ttotalDisk\x12%\n" +
	"\x0eavailable_disk\x18\x04 \x01(\x03R\ravailableDisk\x12\x1b\n" +
	"\tcpu_usage\x18\x05 \x01(\x01R\bcpuUsage\"\xb0\x01\n" +
	"\x1dGenerateAttackScenarioRequest\x12-\n" +
	"\x12target_description\x18\x01 \x01(\tR\x11targetDescription\x12E\n" +
	"\fmax_severity\x18\x02 \x01(\x0e2\".burndevice.v1.DestructionSeverityR\vmaxSeverity\x12\x19\n" +
	"\bai_model\x18\x03 \x01(\tR\aaiModel\"\xe7\x01\n" +
	"\x1eGenerateAttackScenarioResponse\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12/\n" +
	"\x05steps\x18\x03 \x03(\v2\x19.burndevice.v1.AttackStepR\x05steps\x12Q\n" +
	"\x12estimated_severity\x18\x04 \x01(\x0e2\".burndevice.v1.DestructionSeverityR\x11estimatedSeverity\"\xb0\x01\n" +
	"\n" +
	"AttackStep\x12\x14\n" +
	"\x05order\x18\x01 \x01(\x05R\x05order\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.burndevice.v1.DestructionTypeR\x04type\x12\x18\n" +
	"\atargets\x18\x04 \x03(\tR\atargets\x12\x1c\n" +
	"\trationale\x18\x05 \x01(\tR\trationale*\xe5\x02\n" +
	"\x0fDestructionType\x12 \n" +
	"\x1cDESTRUCTION_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eDESTRUCTION_TYPE_FILE_DELETION\x10\x01\x12(\n" +
	"$DESTRUCTION_TYPE_REGISTRY_CORRUPTION\x10\x02\x12(\n" +
	"$DESTRUCTION_TYPE_SERVICE_TERMINATION\x10\x03\x12&\n" +
	"\"DESTRUCTION_TYPE_MEMORY_EXHAUSTION\x10\x04\x12\x1e\n" +
	"\x1aDESTRUCTION_TYPE_DISK_FILL\x10\x05\x12'\n" +
	"#DESTRUCTION_TYPE_NETWORK_DISRUPTION\x10\x06\x12$\n" +
	" DESTRUCTION_TYPE_BOOT_CORRUPTION\x10\a\x12!\n" +
	"\x1dDESTRUCTION_TYPE_KERNEL_PANIC\x10\b*\xbc\x01\n" +
	"\x13DestructionSeverity\x12$\n" +
	" DESTRUCTION_SEVERITY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DESTRUCTION_SEVERITY_LOW\x10\x01\x12\x1f\n" +
	"\x1bDESTRUCTION_SEVERITY_MEDIUM\x10\x02\x12\x1d\n" +
	"\x19DESTRUCTION_SEVERITY_HIGH\x10\x03\x12!\n" +
	"\x1dDESTRUCTION_SEVERITY_CRITICAL\x10\x04*\xf3\x01\n" +
	"\x14DestructionEventType\x12&\n" +
	"\"DESTRUCTION_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eDESTRUCTION_EVENT_TYPE_STARTED\x10\x01\x12#\n" +
	"\x1fDESTRUCTION_EVENT_TYPE_PROGRESS\x10\x02\x12$\n" +
	" DESTRUCTION_EVENT_TYPE_COMPLETED\x10\x03\x12 \n" +
	"\x1cDESTRUCTION_EVENT_TYPE_ERROR\x10\x04\x12\"\n" +
	"\x1eDESTRUCTION_EVENT_TYPE_WARNING\x10\x052\xbb\x03\n" +
	"\x11BurnDeviceService\x12i\n" +
	"\x12ExecuteDestruction\x12(.burndevice.v1.ExecuteDestructionRequest\x1a).burndevice.v1.ExecuteDestructionResponse\x12Z\n" +
	"\rGetSystemInfo\x12#.burndevice.v1.GetSystemInfoRequest\x1a$.burndevice.v1.GetSystemInfoResponse\x12u\n" +
	"\x16GenerateAttackScenario\x12,.burndevice.v1.GenerateAttackScenarioRequest\x1a-.burndevice.v1.GenerateAttackScenarioResponse\x12h\n" +
	"\x11StreamDestruction\x12'.burndevice.v1.StreamDestructionRequest\x1a(.burndevice.v1.StreamDestructionResponse0\x01B=Z;github.com/BurnDevice/BurnDevice/burndevice/v1;burndevicev1b\x06proto3"

var (
	file_burndevice_v1_service_proto_rawDescOnce sync.Once
	file_burndevice_v1_service_proto_rawDescData []byte
)

func file_burndevice_v1_service_proto_rawDescGZIP() []byte {
	file_burndevice_v1_service_proto_rawDescOnce.Do(func() {
		file_burndevice_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_burndevice_v1_service_proto_rawDesc), len(file_burndevice_v1_service_proto_rawDesc)))
	})
	return file_burndevice_v1_service_proto_rawDescData
}

var file_burndevice_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_burndevice_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_burndevice_v1_service_proto_goTypes = []any{
	(DestructionType)(0),                   // 0: burndevice.v1.DestructionType
	(DestructionSeverity)(0),               // 1: burndevice.v1.DestructionSeverity
	(DestructionEventType)(0),              // 2: burndevice.v1.DestructionEventType
	(*ExecuteDestructionRequest)(nil),      // 3: burndevice.v1.ExecuteDestructionRequest
	(*ExecuteDestructionResponse)(nil),     // 4: burndevice.v1.ExecuteDestructionResponse
	(*StreamDestructionRequest)(nil),       // 5: burndevice.v1.StreamDestructionRequest
	(*StreamDestructionResponse)(nil),      // 6: burndevice.v1.StreamDestructionResponse
	(*DestructionResult)(nil),              // 7: burndevice.v1.DestructionResult
	(*DestructionMetrics)(nil),             // 8: burndevice.v1.DestructionMetrics
	(*GetSystemInfoRequest)(nil),           // 9: burndevice.v1.GetSystemInfoRequest
	(*GetSystemInfoResponse)(nil),          // 10: burndevice.v1.GetSystemInfoResponse
	(*SystemResources)(nil),                // 11: burndevice.v1.SystemResources
	(*GenerateAttackScenarioRequest)(nil),  // 12: burndevice.v1.GenerateAttackScenarioRequest
	(*GenerateAttackScenarioResponse)(nil), // 13: burndevice.v1.GenerateAttackScenarioResponse
	(*AttackStep)(nil),                     // 14: burndevice.v1.AttackStep
	(*timestamppb.Timestamp)(nil),          // 15: google.protobuf.Timestamp
}
var file_burndevice_v1_service_proto_depIdxs = []int32{
	0,  // 0: burndevice.v1.ExecuteDestructionRequest.type:type_name -> burndevice.v1.DestructionType
	1,  // 1: burndevice.v1.ExecuteDestructionRequest.severity:type_name -> burndevice.v1.DestructionSeverity
	7,  // 2: burndevice.v1.ExecuteDestructionResponse.results:type_name -> burndevice.v1.DestructionResult
	15, // 3: burndevice.v1.ExecuteDestructionResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 4: burndevice.v1.StreamDestructionRequest.type:type_name -> burndevice.v1.DestructionType
	1,  // 5: burndevice.v1.StreamDestructionRequest.severity:type_name -> burndevice.v1.DestructionSeverity
	15, // 6: burndevice.v1.StreamDestructionResponse.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 7: burndevice.v1.StreamDestructionResponse.type:type_name -> burndevice.v1.DestructionEventType
	8,  // 8: burndevice.v1.DestructionResult.metrics:type_name -> burndevice.v1.DestructionMetrics
	11, // 9: burndevice.v1.GetSystemInfoResponse.resources:type_name -> burndevice.v1.SystemResources
	1,  // 10: burndevice.v1.GenerateAttackScenarioRequest.max_severity:type_name -> burndevice.v1.DestructionSeverity
	14, // 11: burndevice.v1.GenerateAttackScenarioResponse.steps:type_name -> burndevice.v1.AttackStep
	1,  // 12: burndevice.v1.GenerateAttackScenarioResponse.estimated_severity:type_name -> burndevice.v1.DestructionSeverity
	0,  // 13: burndevice.v1.AttackStep.type:type_name -> burndevice.v1.DestructionType
	3,  // 14: burndevice.v1.BurnDeviceService.ExecuteDestruction:input_type -> burndevice.v1.ExecuteDestructionRequest
	9,  // 15: burndevice.v1.BurnDeviceService.GetSystemInfo:input_type -> burndevice.v1.GetSystemInfoRequest
	12, // 16: burndevice.v1.BurnDeviceService.GenerateAttackScenario:input_type -> burndevice.v1.GenerateAttackScenarioRequest
	5,  // 17: burndevice.v1.BurnDeviceService.StreamDestruction:input_type -> burndevice.v1.StreamDestructionRequest
	4,  // 18: burndevice.v1.BurnDeviceService.ExecuteDestruction:output_type -> burndevice.v1.ExecuteDestructionResponse
	10, // 19: burndevice.v1.BurnDeviceService.GetSystemInfo:output_type -> burndevice.v1.GetSystemInfoResponse
	13, // 20: burndevice.v1.BurnDeviceService.GenerateAttackScenario:output_type -> burndevice.v1.GenerateAttackScenarioResponse
	6,  // 21: burndevice.v1.BurnDeviceService.StreamDestruction:output_type -> burndevice.v1.StreamDestructionResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_burndevice_v1_service_proto_init() }
func file_burndevice_v1_service_proto_init() {
	if File_burndevice_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_burndevice_v1_service_proto_rawDesc), len(file_burndevice_v1_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_burndevice_v1_service_proto_goTypes,
		DependencyIndexes: file_burndevice_v1_service_proto_depIdxs,
		EnumInfos:         file_burndevice_v1_service_proto_enumTypes,
		MessageInfos:      file_burndevice_v1_service_proto_msgTypes,
	}.Build()
	File_burndevice_v1_service_proto = out.File
	file_burndevice_v1_service_proto_goTypes = nil
	file_burndevice_v1_service_proto_depIdxs = nil
}
